export type AgentState = 'INTAKE' | 'POLICY_CHECK' | 'KNOWLEDGE_RETRIEVAL' | 'VENDOR_SELECTION' | 'RFQ_GENERATION' | 'RFQ_SENT' | 'WAITING_FOR_VENDOR' | 'OFFER_RECEIVED' | 'OFFER_ANALYSIS' | 'NEGOTIATION_PLANNING' | 'ACTION_PROPOSED' | 'CRITIC_REVIEW' | 'POLICY_REVIEW' | 'EXECUTION' | 'HUMAN_REVIEW' | 'ACCEPTED' | 'STOPPED' | 'FAILED';
export type EventType = 'REQUIREMENT_EXTRACTED' | 'POLICY_RETRIEVED' | 'VENDORS_SELECTED' | 'RFQ_SENT' | 'VENDOR_RESPONSE_RECEIVED' | 'OFFER_PARSED' | 'NEGOTIATION_PLAN_CREATED' | 'ACTION_PROPOSED' | 'CRITIC_STARTED' | 'CRITIC_RESULT' | 'POLICY_RESULT' | 'ACTION_BLOCKED' | 'COUNTEROFFER_SENT' | 'HUMAN_REVIEW_REQUIRED' | 'HUMAN_APPROVED' | 'HUMAN_REJECTED' | 'RETRY_STARTED' | 'FALLBACK_ACTIVATED' | 'NEGOTIATION_STOPPED' | 'DEAL_ACCEPTED' | 'AGENT_FAILED';

export type ProcurementRequest = { item: string; quantity: number; targetUnitPrice: number | null; maximumUnitPrice: number; deliveryDays: number; minimumWarrantyMonths: number; maximumAdvancePaymentPercent: number; negotiableTerms: string[]; nonNegotiableTerms: string[] };
export type Vendor = { id: string; name: string; category: string; approved: boolean; reliabilityScore: number; contact: string; behavior: { initial: Offer; rounds: Offer[]; failure?: 'DELAY_ONCE' | 'MALFORMED_ONCE' | 'TEMPORARY_FAILURE_ONCE' } };
export type Offer = { id: string; requestId: string; vendorId: string; roundNumber: number; rawResponse: string; unitPrice: number; totalPrice: number; deliveryDays: number; warrantyMonths: number; advancePaymentPercent: number; paymentTerms: string; validityDays: number | null; additionalConditions: string[]; extractionConfidence: number; criticStatus?: CriticResult['decision']; policyStatus?: PolicyResult['decision'] };
export type ProposedTerms = { unitPrice: number; deliveryDays?: number; warrantyMonths?: number; advancePaymentPercent?: number; paymentTerms?: string };
export type AgentAction = { type: 'SEND_COUNTER'; vendorId: string; message: string; proposedTerms: ProposedTerms; rationale: string } | { type: 'ACCEPT'; vendorId: string; offerId: string; rationale: string } | { type: 'ESCALATE'; reason: string } | { type: 'STOP'; reason: string };
export type CriticResult = { decision: 'PASS' | 'WARN' | 'BLOCK'; confidence: number; policyViolations: string[]; concerns: string[]; evidence: string[]; requiresHumanReview: boolean };
export type PolicyResult = { decision: 'PASS' | 'BLOCK' | 'HUMAN_REVIEW'; violations: string[]; warnings: string[]; evidence: string[] };
export type DecisionResult = { decision: 'EXECUTE' | 'BLOCK' | 'HUMAN_REVIEW' | 'STOP'; reason: string };
export type NegotiationMessage = { id: string; vendorId: string; sender: 'AGENT' | 'VENDOR' | 'SYSTEM'; content: string; roundNumber: number; messageType: string; createdAt: string };
export type AgentEvent = { id: string; sessionId: string; type: EventType; state: AgentState; message: string; metadata: Record<string, unknown>; createdAt: string };
export type ConcessionBudget = { price: number; advancePayment: number; deliveryDays: number; warrantyMonths: number };
export type ModelRun = { model: string; role: 'NEGOTIATOR' | 'CRITIC' | 'FALLBACK'; durationMs: number; retryCount: number; fallback: boolean; success: boolean; usage?: { inputTokens?: number; outputTokens?: number } };
export type HumanReview = { id: string; reason: string; proposedAction: AgentAction; evidence: string[]; status: 'PENDING' | 'APPROVED' | 'REJECTED' | 'STOPPED'; createdAt: string; resolvedAt?: string };
export type EvaluationResult = { caseId: string; passed: boolean; expectedBehavior: string; actualBehavior: string; details: string[] };
export type EvaluationRun = { id: string; total: number; passed: number; failed: number; metrics: Record<string, number>; results: EvaluationResult[]; createdAt: string };
export type NegotiationSession = { id: string; requestId: string; currentVendorId: string | null; currentRound: number; originalRequest: ProcurementRequest; vendors: Vendor[]; offers: Offer[]; messages: NegotiationMessage[]; events: AgentEvent[]; currentBestOffer: Offer | null; targetUnitPrice: number | null; maximumUnitPrice: number; minimumWarrantyMonths: number; maximumDeliveryDays: number; maximumAdvancePaymentPercent: number; concessionBudget: ConcessionBudget; riskScore: number; confidence: number; currentState: AgentState; pendingAction: AgentAction | null; criticResult: CriticResult | null; policyResult: PolicyResult | null; stopReason: string | null; modelRuns: ModelRun[]; humanReview: HumanReview | null; startedAt: string; updatedAt: string };

export const now = () => new Date().toISOString();
export const createId = () => crypto.randomUUID();
